spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bogdanchik0536@gmail.com
    password: riemlmuwvqpladnt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  sheets:
    spreadsheet-id: "1ur7DWpfp4O_guZJtzmpi_KT3HA8KwL-hCLrLHOa21Lk"
    range: "A1:Z100"
    api-key: "AIzaSyB42E_9CHbIdscwFYs-0JpK1SvhAZqBkHg"

app:
  mail:
    to-address: bogdanchik0536@gmail.com"