spring.application.name=pz1_sokol

# Налаштування відправки пошти через особистий Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=bogbanchik0536@gmail.com
spring.mail.password=riemlmuwvqpladnt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Налаштування Google Sheets API
google.sheets.spreadsheet-id=1ur7DWpfp4O_guZJtzmpi_KT3HA8KwL-hCLrLHOa21Lk
# Діапазон зчитування: розширено до 100 рядків і 26 колонок (A-Z)
google.sheets.range=A1:Z100
google.sheets.api-key=AIzaSyB42E_9CHbIdscwFYs-0JpK1SvhAZqBkHg